#[derive(Clone, Copy, Debug)]
pub(crate) struct SageExportTarget {
    pub(crate) import_module: &'static str,
    pub(crate) name: &'static str,
    pub(crate) source_module: &'static str,
    pub(crate) source_name: &'static str,
}

pub(crate) const SAGE_EXPORT_MAP: &[SageExportTarget] = &[
    SageExportTarget {
        import_module: "sage.all",
        name: "GF",
        source_module: "sage.rings.finite_rings.finite_field_constructor",
        source_name: "GF",
    },
    SageExportTarget {
        import_module: "sage.rings.finite_rings.all",
        name: "GF",
        source_module: "sage.rings.finite_rings.finite_field_constructor",
        source_name: "GF",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "PolynomialRing",
        source_module: "sage.rings.polynomial.polynomial_ring_constructor",
        source_name: "PolynomialRing",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "NumberField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "NumberField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "NumberField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "NumberField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "CyclotomicField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "CyclotomicField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "CyclotomicField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "CyclotomicField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "QuadraticField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "QuadraticField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "QuadraticField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "QuadraticField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "Graph",
        source_module: "sage.graphs.graph",
        source_name: "Graph",
    },
    SageExportTarget {
        import_module: "sage.graphs.all",
        name: "Graph",
        source_module: "sage.graphs.graph",
        source_name: "Graph",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "DiGraph",
        source_module: "sage.graphs.digraph",
        source_name: "DiGraph",
    },
    SageExportTarget {
        import_module: "sage.graphs.all",
        name: "DiGraph",
        source_module: "sage.graphs.digraph",
        source_name: "DiGraph",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "EllipticCurve",
        source_module: "sage.schemes.elliptic_curves.constructor",
        source_name: "EllipticCurve",
    },
    SageExportTarget {
        import_module: "sage.schemes.elliptic_curves.all",
        name: "EllipticCurve",
        source_module: "sage.schemes.elliptic_curves.constructor",
        source_name: "EllipticCurve",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "Polyhedron",
        source_module: "sage.geometry.polyhedron.constructor",
        source_name: "Polyhedron",
    },
    SageExportTarget {
        import_module: "sage.geometry.all",
        name: "Polyhedron",
        source_module: "sage.geometry.polyhedron.constructor",
        source_name: "Polyhedron",
    },
    SageExportTarget {
        import_module: "sage.geometry.polyhedron.all",
        name: "Polyhedron",
        source_module: "sage.geometry.polyhedron.constructor",
        source_name: "Polyhedron",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "matrix",
        source_module: "sage.matrix.constructor",
        source_name: "matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "matrix",
        source_module: "sage.matrix.constructor",
        source_name: "matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "zero_matrix",
        source_module: "sage.matrix.special",
        source_name: "zero_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "zero_matrix",
        source_module: "sage.matrix.special",
        source_name: "zero_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "random_matrix",
        source_module: "sage.matrix.special",
        source_name: "random_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "random_matrix",
        source_module: "sage.matrix.special",
        source_name: "random_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "identity_matrix",
        source_module: "sage.matrix.special",
        source_name: "identity_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "identity_matrix",
        source_module: "sage.matrix.special",
        source_name: "identity_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "column_matrix",
        source_module: "sage.matrix.special",
        source_name: "column_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "column_matrix",
        source_module: "sage.matrix.special",
        source_name: "column_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "block_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "block_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "block_diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "block_diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "ones_matrix",
        source_module: "sage.matrix.special",
        source_name: "ones_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "ones_matrix",
        source_module: "sage.matrix.special",
        source_name: "ones_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "elementary_matrix",
        source_module: "sage.matrix.special",
        source_name: "elementary_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "elementary_matrix",
        source_module: "sage.matrix.special",
        source_name: "elementary_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "companion_matrix",
        source_module: "sage.matrix.special",
        source_name: "companion_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "companion_matrix",
        source_module: "sage.matrix.special",
        source_name: "companion_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "vector",
        source_module: "sage.modules.free_module_element",
        source_name: "vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "vector",
        source_module: "sage.modules.free_module_element",
        source_name: "vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "zero_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "zero_vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "zero_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "zero_vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "random_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "random_vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "random_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "random_vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "ZZ",
        source_module: "sage.rings.integer_ring",
        source_name: "ZZ",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "QQ",
        source_module: "sage.rings.rational_field",
        source_name: "QQ",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "SR",
        source_module: "sage.symbolic.ring",
        source_name: "SR",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "var",
        source_module: "sage.calculus.var",
        source_name: "var",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "latex",
        source_module: "sage.misc.latex",
        source_name: "latex",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "set_random_seed",
        source_module: "sage.misc.randstate",
        source_name: "set_random_seed",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "RR",
        source_module: "sage.rings.real_mpfr",
        source_name: "RR",
    },
];
