use crate::{SageOwnerModuleSpec, SageOwnerType};

pub(crate) const SAGE_OWNER_METHOD_MODULES: &[SageOwnerModuleSpec] = &[
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Matrix,
        module: "sage.matrix",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FreeModule,
        module: "sage.modules.free_module",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.rings.polynomial.polynomial_ring",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.rings.polynomial.multi_polynomial_libsingular",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::UnivariatePolynomialRing,
        module: "sage.rings.polynomial.polynomial_ring",
        recursive: false,
        priority: 0,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::MultivariatePolynomialRing,
        module: "sage.rings.polynomial.multi_polynomial_libsingular",
        recursive: false,
        priority: 0,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::MultivariatePolynomialRing,
        module: "sage.rings.polynomial.multi_polynomial_ring",
        recursive: false,
        priority: 5,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.parent_gens",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.parent",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.category_object",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polynomial_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.multi_polynomial_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polynomial_element_generic",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.multi_polynomial",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polydict",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Ideal,
        module: "sage.rings.polynomial.multi_polynomial_ideal",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Field,
        module: "sage.rings.finite_rings",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FieldElement,
        module: "sage.rings.finite_rings",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FieldElement,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Vector,
        module: "sage.modules.free_module_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Vector,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Graph,
        module: "sage.graphs",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::EllipticCurve,
        module: "sage.schemes.elliptic_curves",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::NumberField,
        module: "sage.rings.number_field",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::NumberFieldElement,
        module: "sage.rings.number_field.number_field_element",
        recursive: false,
        priority: 0,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Polyhedron,
        module: "sage.geometry.polyhedron",
        recursive: true,
        priority: 10,
    },
];
