use super::{SageMethodAliasSpec, SageMethodSpec, SageOwnerModuleSpec, SageOwnerType};

#[derive(Clone, Copy, Debug)]
pub(super) struct SageExportTarget {
    pub(super) import_module: &'static str,
    pub(super) name: &'static str,
    pub(super) source_module: &'static str,
    pub(super) source_name: &'static str,
}

pub(super) const SAGE_EXPORT_MAP: &[SageExportTarget] = &[
    SageExportTarget {
        import_module: "sage.all",
        name: "GF",
        source_module: "sage.rings.finite_rings.finite_field_constructor",
        source_name: "GF",
    },
    SageExportTarget {
        import_module: "sage.rings.finite_rings.all",
        name: "GF",
        source_module: "sage.rings.finite_rings.finite_field_constructor",
        source_name: "GF",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "PolynomialRing",
        source_module: "sage.rings.polynomial.polynomial_ring_constructor",
        source_name: "PolynomialRing",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "NumberField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "NumberField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "NumberField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "NumberField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "CyclotomicField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "CyclotomicField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "CyclotomicField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "CyclotomicField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "QuadraticField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "QuadraticField",
    },
    SageExportTarget {
        import_module: "sage.rings.number_field.all",
        name: "QuadraticField",
        source_module: "sage.rings.number_field.number_field",
        source_name: "QuadraticField",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "Graph",
        source_module: "sage.graphs.graph",
        source_name: "Graph",
    },
    SageExportTarget {
        import_module: "sage.graphs.all",
        name: "Graph",
        source_module: "sage.graphs.graph",
        source_name: "Graph",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "DiGraph",
        source_module: "sage.graphs.digraph",
        source_name: "DiGraph",
    },
    SageExportTarget {
        import_module: "sage.graphs.all",
        name: "DiGraph",
        source_module: "sage.graphs.digraph",
        source_name: "DiGraph",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "EllipticCurve",
        source_module: "sage.schemes.elliptic_curves.constructor",
        source_name: "EllipticCurve",
    },
    SageExportTarget {
        import_module: "sage.schemes.elliptic_curves.all",
        name: "EllipticCurve",
        source_module: "sage.schemes.elliptic_curves.constructor",
        source_name: "EllipticCurve",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "matrix",
        source_module: "sage.matrix.constructor",
        source_name: "matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "matrix",
        source_module: "sage.matrix.constructor",
        source_name: "matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "zero_matrix",
        source_module: "sage.matrix.special",
        source_name: "zero_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "zero_matrix",
        source_module: "sage.matrix.special",
        source_name: "zero_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "random_matrix",
        source_module: "sage.matrix.special",
        source_name: "random_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "random_matrix",
        source_module: "sage.matrix.special",
        source_name: "random_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "identity_matrix",
        source_module: "sage.matrix.special",
        source_name: "identity_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "identity_matrix",
        source_module: "sage.matrix.special",
        source_name: "identity_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "column_matrix",
        source_module: "sage.matrix.special",
        source_name: "column_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "column_matrix",
        source_module: "sage.matrix.special",
        source_name: "column_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "block_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "block_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "block_diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "block_diagonal_matrix",
        source_module: "sage.matrix.special",
        source_name: "block_diagonal_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "ones_matrix",
        source_module: "sage.matrix.special",
        source_name: "ones_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "ones_matrix",
        source_module: "sage.matrix.special",
        source_name: "ones_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "elementary_matrix",
        source_module: "sage.matrix.special",
        source_name: "elementary_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "elementary_matrix",
        source_module: "sage.matrix.special",
        source_name: "elementary_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "companion_matrix",
        source_module: "sage.matrix.special",
        source_name: "companion_matrix",
    },
    SageExportTarget {
        import_module: "sage.matrix.all",
        name: "companion_matrix",
        source_module: "sage.matrix.special",
        source_name: "companion_matrix",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "vector",
        source_module: "sage.modules.free_module_element",
        source_name: "vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "vector",
        source_module: "sage.modules.free_module_element",
        source_name: "vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "zero_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "zero_vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "zero_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "zero_vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "random_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "random_vector",
    },
    SageExportTarget {
        import_module: "sage.modules.all",
        name: "random_vector",
        source_module: "sage.modules.free_module_element",
        source_name: "random_vector",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "ZZ",
        source_module: "sage.rings.integer_ring",
        source_name: "ZZ",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "QQ",
        source_module: "sage.rings.rational_field",
        source_name: "QQ",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "SR",
        source_module: "sage.symbolic.ring",
        source_name: "SR",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "var",
        source_module: "sage.calculus.var",
        source_name: "var",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "latex",
        source_module: "sage.misc.latex",
        source_name: "latex",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "set_random_seed",
        source_module: "sage.misc.randstate",
        source_name: "set_random_seed",
    },
    SageExportTarget {
        import_module: "sage.all",
        name: "RR",
        source_module: "sage.rings.real_mpfr",
        source_name: "RR",
    },
];

pub(super) const SAGE_OWNER_METHOD_MODULES: &[SageOwnerModuleSpec] = &[
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Matrix,
        module: "sage.matrix",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FreeModule,
        module: "sage.modules.free_module",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.rings.polynomial.polynomial_ring",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.rings.polynomial.multi_polynomial_libsingular",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.parent_gens",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.parent",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialRing,
        module: "sage.structure.category_object",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polynomial_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.multi_polynomial_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polynomial_element_generic",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.multi_polynomial",
        recursive: false,
        priority: 20,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.rings.polynomial.polydict",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::PolynomialElement,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Ideal,
        module: "sage.rings.polynomial.multi_polynomial_ideal",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Field,
        module: "sage.rings.finite_rings",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FieldElement,
        module: "sage.rings.finite_rings",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::FieldElement,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Vector,
        module: "sage.modules.free_module_element",
        recursive: false,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Vector,
        module: "sage.structure.element",
        recursive: false,
        priority: 30,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::Graph,
        module: "sage.graphs",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::EllipticCurve,
        module: "sage.schemes.elliptic_curves",
        recursive: true,
        priority: 10,
    },
    SageOwnerModuleSpec {
        owner_type: SageOwnerType::NumberField,
        module: "sage.rings.number_field",
        recursive: true,
        priority: 10,
    },
];

pub(super) const SAGE_METHOD_SPECS: &[SageMethodSpec] = &[
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "rank",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "base_ring",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "dimensions",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "list",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "change_ring",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "pivots",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "rows",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "row",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "column",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "augment",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "matrix_from_columns",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "matrix_from_rows",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "matrix_from_rows_and_columns",
        module: "sage.matrix.matrix1",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "transpose",
        module: "sage.matrix.matrix_dense",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "solve_right",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "subs",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "right_kernel",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "det",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "inverse",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "column_space",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "charpoly",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "adjugate",
        module: "sage.matrix.matrix2",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "nrows",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Matrix,
        member: "ncols",
        module: "sage.matrix.matrix0",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FreeModule,
        member: "basis",
        module: "sage.modules.free_module",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FreeModule,
        member: "basis_matrix",
        module: "sage.modules.free_module",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FreeModule,
        member: "dimension",
        module: "sage.modules.free_module",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FreeModule,
        member: "change_ring",
        module: "sage.modules.free_module",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "gens",
        module: "sage.structure.parent_gens",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "gen",
        module: "sage.structure.parent_gens",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "ideal",
        module: "sage.rings.polynomial.multi_polynomial_libsingular",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "base_ring",
        module: "sage.structure.category_object",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "hom",
        module: "sage.structure.parent",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialRing,
        member: "lagrange_polynomial",
        module: "sage.rings.polynomial.polynomial_ring",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "degree",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "factor",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "monic",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "map_coefficients",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "monomial_coefficient",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "constant_coefficient",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "base_ring",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "change_ring",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "list",
        module: "sage.rings.polynomial.polynomial_element_generic",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "is_zero",
        module: "sage.structure.element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "parent",
        module: "sage.structure.element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "dict",
        module: "sage.rings.polynomial.polydict",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "subs",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "total_degree",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "is_constant",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "gcd",
        module: "sage.rings.polynomial.multi_polynomial",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "resultant",
        module: "sage.rings.polynomial.multi_polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "derivative",
        module: "sage.rings.polynomial.multi_polynomial",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::PolynomialElement,
        member: "roots",
        module: "sage.rings.polynomial.polynomial_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Ideal,
        member: "dimension",
        module: "sage.rings.polynomial.multi_polynomial_ideal",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Ideal,
        member: "variety",
        module: "sage.rings.polynomial.multi_polynomial_ideal",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Field,
        member: "random_element",
        module: "sage.rings.finite_rings.finite_field_base",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Field,
        member: "order",
        module: "sage.rings.finite_rings.finite_field_base",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Field,
        member: "from_integer",
        module: "sage.rings.finite_rings.finite_field_base",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FieldElement,
        member: "parent",
        module: "sage.structure.element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FieldElement,
        member: "polynomial",
        module: "sage.rings.finite_rings.element_givaro",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::FieldElement,
        member: "to_integer",
        module: "sage.rings.finite_rings.element_base",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Vector,
        member: "base_ring",
        module: "sage.structure.element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Vector,
        member: "change_ring",
        module: "sage.modules.free_module_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Vector,
        member: "list",
        module: "sage.modules.free_module_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Vector,
        member: "row",
        module: "sage.modules.free_module_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Vector,
        member: "column",
        module: "sage.modules.free_module_element",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "vertices",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "edges",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "neighbors",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "degree",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "shortest_path",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "adjacency_matrix",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "plot",
        module: "sage.graphs.generic_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::Graph,
        member: "is_connected",
        module: "sage.graphs.base.c_graph",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "base_ring",
        module: "sage.schemes.elliptic_curves.ell_generic",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "gens",
        module: "sage.schemes.elliptic_curves.ell_generic",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "plot",
        module: "sage.schemes.elliptic_curves.ell_generic",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "points",
        module: "sage.schemes.elliptic_curves.ell_finite_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "cardinality",
        module: "sage.schemes.elliptic_curves.ell_finite_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "torsion_subgroup",
        module: "sage.schemes.elliptic_curves.ell_finite_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "rank",
        module: "sage.schemes.elliptic_curves.ell_rational_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "integral_points",
        module: "sage.schemes.elliptic_curves.ell_rational_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "ring_of_integers",
        module: "sage.rings.number_field.number_field_base",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "degree",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "absolute_degree",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "relative_degree",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "discriminant",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "gen",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "gens",
        module: "sage.rings.number_field.number_field_rel",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "embeddings",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "places",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "signature",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "class_group",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "unit_group",
        module: "sage.rings.number_field.number_field",
    },
    SageMethodSpec {
        owner_type: SageOwnerType::NumberField,
        member: "is_isomorphic",
        module: "sage.rings.number_field.number_field",
    },
];

pub(super) const SAGE_METHOD_ALIAS_SPECS: &[SageMethodAliasSpec] = &[
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "random",
        source_name: "random_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "identity",
        source_name: "identity_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "column",
        source_name: "column_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "diagonal",
        source_name: "diagonal_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "zero",
        source_name: "zero_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "ones",
        source_name: "ones_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "block",
        source_name: "block_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::MatrixConstructor,
        member: "block_diagonal",
        source_name: "block_diagonal_matrix",
        module: "sage.matrix.special",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::EllipticCurve,
        member: "order",
        source_name: "cardinality",
        module: "sage.schemes.elliptic_curves.ell_finite_field",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::FieldElement,
        member: "integer_representation",
        source_name: "to_integer",
        module: "sage.rings.finite_rings.element_base",
    },
    SageMethodAliasSpec {
        owner_type: SageOwnerType::FieldElement,
        member: "_integer_representation",
        source_name: "_integer_representation",
        module: "sage.rings.finite_rings.element_givaro",
    },
];
